# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Write Env File
      run: |
        pip install -r requirements.txt
        echo "USERNAME=${{secrets.USERNAME}}" >> ".env"
        echo "PASSWORD=${{secrets.PASSWORD}}" >> ".env"
        echo "LOCATION=${{secrets.LOCATION}}" >> ".env"
        echo "COORDINATES=${{secrets.COORDINATES}}" >> ".env"
    - name: Test with pytest
      run: |
        python main.py
